using CareAssist.Application.Abstractions.AI;
using CareAssist.Contracts.AI;
using Microsoft.Extensions.Logging;

namespace CareAssist.Infrastructure.AI.Fake;

public sealed class FakeChatCompletionService : IChatCompletionService
{
    private readonly ILogger<FakeChatCompletionService> _logger;

    public FakeChatCompletionService(ILogger<FakeChatCompletionService> logger)
    {
        _logger = logger;
    }

    public Task<ChatResponse> GenerateResponseAsync(IEnumerable<ChatMessage> messages, 
        CancellationToken cancellationToken = default)
    {

        _logger.LogInformation("FakeChatCompletionService.GenerateResponseAsync called with {MessageCount} messages.",
            messages.Count());

        return Task.FromResult(new ChatResponse(
            " - > This is a fake response generated by the FakeChatCompletionService.",
            "fake-model"
        ));
    }
}
