<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CareAssist.Application\CareAssist.Application.csproj" />
    <ProjectReference Include="..\CareAssist.Domain\CareAssist.Domain.csproj" />
  </ItemGroup>

</Project>
